#!/bin/bash
exec > /var/log/user-data.log 2>&1
set -x

echo "=== DAY 0 - Oracle XE 21c Database Server Setup ==="
echo "Start time: $(date)"

#---------------------------------------------------------------------------
# STEP 1 - Installation of Docker Compose
#---------------------------------------------------------------------------
echo "=== STEP 1 - Installing Docker Compose ==="

sudo apt-get remove docker docker-engine docker.io containerd runc -y
sudo apt-get update
sudo apt-get install -y ca-certificates curl gnupg lsb-release

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker.gpg

echo \
"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu \
$(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

docker --version
docker compose version

sudo usermod -aG docker ubuntu

#---------------------------------------------------------------------------
# STEP 2 - Install AWS and configure AWS
#---------------------------------------------------------------------------
echo "=== STEP 2 - Installing and Configuring AWS CLI ==="

sudo apt update
sudo apt install -y unzip curl

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip -o awscliv2.zip
sudo ./aws/install
rm -rf awscliv2.zip aws

aws --version

%{ if aws_access_key_id != "" && aws_secret_access_key != "" }
# Configure AWS credentials for ubuntu user
sudo -u ubuntu aws configure set aws_access_key_id ${aws_access_key_id}
sudo -u ubuntu aws configure set aws_secret_access_key ${aws_secret_access_key}
sudo -u ubuntu aws configure set region ${aws_region}
sudo -u ubuntu aws configure set output json

# Also configure for root
aws configure set aws_access_key_id ${aws_access_key_id}
aws configure set aws_secret_access_key ${aws_secret_access_key}
aws configure set region ${aws_region}
aws configure set output json
%{ endif }

#---------------------------------------------------------------------------
# STEP 3 - Install Oracle Instant Client (includes impdp)
#---------------------------------------------------------------------------
echo "=== STEP 3 - Installing Oracle Instant Client ==="

sudo apt update
sudo apt install -y unzip libaio1t64 || sudo apt install -y unzip libaio1

mkdir -p /home/ubuntu/oracle
cd /home/ubuntu/oracle

wget https://download.oracle.com/otn_software/linux/instantclient/219000/instantclient-basiclite-linux.x64-21.9.0.0.0dbru.zip
wget https://download.oracle.com/otn_software/linux/instantclient/219000/instantclient-tools-linux.x64-21.9.0.0.0dbru.zip

unzip -o instantclient-basiclite-*.zip
unzip -o instantclient-tools-*.zip
rm -f *.zip

chown -R ubuntu:ubuntu /home/ubuntu/oracle

# Configure environment for ubuntu user
echo 'export LD_LIBRARY_PATH=$HOME/oracle/instantclient_21_9' >> /home/ubuntu/.bashrc
echo 'export PATH=$HOME/oracle/instantclient_21_9:$PATH' >> /home/ubuntu/.bashrc

sudo ln -sf /lib/x86_64-linux-gnu/libaio.so.1t64 /lib/x86_64-linux-gnu/libaio.so.1 2>/dev/null || true
sudo ldconfig

#---------------------------------------------------------------------------
# STEP 7 - Creation of docker compose file
#---------------------------------------------------------------------------
echo "=== STEP 7 - Creating Docker Compose Configuration ==="

mkdir -p /home/ubuntu/oracle_xe
cd /home/ubuntu/oracle_xe

cat > /home/ubuntu/oracle_xe/docker-compose.yml << 'COMPOSEEOF'
services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    environment:
      ORACLE_PASSWORD: "${db_password}"
      APP_USER: "${db_user}"
      APP_USER_PASSWORD: "${db_password}"
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
volumes:
  oracle-data:
COMPOSEEOF

chown -R ubuntu:ubuntu /home/ubuntu/oracle_xe

#---------------------------------------------------------------------------
# STEP 8 - Start Oracle XE Container
#---------------------------------------------------------------------------
echo "=== STEP 8 - Starting Oracle XE Container ==="

cd /home/ubuntu/oracle_xe
docker compose up -d

echo "Waiting for Oracle XE to start (this may take 2-3 minutes)..."
sleep 180

# Check container status
docker ps
docker logs oracle-xe | tail -20

#---------------------------------------------------------------------------
# STEP 9 - Create and Run seed.sql
#---------------------------------------------------------------------------
echo "=== STEP 9 - Creating and Running Seed SQL ==="

cat > /home/ubuntu/oracle_xe/seed.sql << 'SQLEOF'
CREATE TABLE customers (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

INSERT INTO customers(name) VALUES ('Alice');
INSERT INTO customers(name) VALUES ('Bob');

COMMIT;
SQLEOF

chown ubuntu:ubuntu /home/ubuntu/oracle_xe/seed.sql

# Wait a bit more and run seed script
sleep 30

docker exec -i oracle-xe bash -lc "sqlplus ${db_user}/${db_password}@XEPDB1" < /home/ubuntu/oracle_xe/seed.sql || {
  echo "First attempt failed, retrying in 60 seconds..."
  sleep 60
  docker exec -i oracle-xe bash -lc "sqlplus ${db_user}/${db_password}@XEPDB1" < /home/ubuntu/oracle_xe/seed.sql
}

# Verify data
echo "=== Verifying Data ==="
docker exec -it oracle-xe bash -lc "sqlplus ${db_user}/${db_password}@XEPDB1 <<SQL
SELECT * FROM customers;
EXIT;
SQL"

#---------------------------------------------------------------------------
# Create Systemd Service for Auto-Start
#---------------------------------------------------------------------------
echo "=== Creating Systemd Service ==="

cat > /etc/systemd/system/oracle-xe-docker.service << 'SYSTEMDEOF'
[Unit]
Description=Oracle XE Docker Compose Service
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/home/ubuntu/oracle_xe
ExecStart=/usr/bin/docker compose up -d
ExecStop=/usr/bin/docker compose down
User=root

[Install]
WantedBy=multi-user.target
SYSTEMDEOF

systemctl daemon-reload
systemctl enable oracle-xe-docker

#---------------------------------------------------------------------------
# Final Output
#---------------------------------------------------------------------------
echo "=== DAY 0 Setup Complete ==="
echo "End time: $(date)"
echo ""
echo "Connection Info:"
echo "  Host: $(hostname -I | awk '{print $1}')"
echo "  Port: 1521"
echo "  Service: XEPDB1"
echo "  User: ${db_user}"
echo ""
echo "Useful Commands:"
echo "  docker logs -f oracle-xe"
echo "  docker exec -it oracle-xe bash -lc 'sqlplus ${db_user}/${db_password}@XEPDB1'"
